import = [
    "~/.config/alacritty/themes/everforest-dark.toml"
]

[font]
normal = { family = "Anonymous Pro" }
size = 10.0

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [{ key = "N", mods = "Shift|Control", action = "CreateNewWindow" },]
